arche/urls.py
# urls.py
from django.urls import path
from arche import views


urlpatterns = [
    path('', views.TopColListView.as_view(), name="top_col_list"),
    path('collection/<int:arche_id>', views.TopColDetailView.as_view(), name="top_col_detail"),
]

djangobaseproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('arche.urls', 'arche'), namespace='arche')),
]

arche/views.py
from django.conf import settings
from django.views.generic import TemplateView
import json

from arche.arche_utils import (
    fetch_data,
    top_col_dict,
    TOP_COL_SIMPLE,
    resource_to_dict,
    filter_by_lang,
    fetch_children
)


ARCHE_API = settings.ARCHE_API


class TopColListView(TemplateView):
    template_name = "arche/top_col_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lang = self.request.GET.get('lang')
        if settings.DEBUG:
            with open("hansi.json", "r") as file:
                top_cols = json.load(file)
        else:
            params = {
                "property[0]": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "value[0]": "https://vocabs.acdh.oeaw.ac.at/schema#TopCollection",
            }
            g = fetch_data(params=params, read_mode='resource')
            g = g.query(TOP_COL_SIMPLE)
            top_cols = top_col_dict(g, lang)
            context["top_cols"] = [value for _, value in top_cols.items()]
            with open('hansi.json', 'w') as file:
                json.dump(top_cols, file, ensure_ascii=False)
        context["top_cols"] = [value for _, value in top_cols.items()]
        return context


class TopColDetailView(TemplateView):
    template_name = "arche/top_col_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lang = self.request.GET.get('lang')
        arche_id = self.kwargs['arche_id']
        url = f"{ARCHE_API}{arche_id}/metadata"
        g = fetch_data(url=url, read_mode='0_0_1_0')
        data = resource_to_dict(g, lang=lang)
        data = filter_by_lang(dict(data[f"{arche_id}"]), lang=lang)
        children = fetch_children(arche_id, lang=lang)
        if settings.DEBUG:
            with open(f"asdf__{arche_id}.json", 'w') as file:
                json.dump(data, file, ensure_ascii=False)
        context["object"] = data
        context["lang"] = lang
        context["arche_id"] = f"{arche_id}"
        context["children"] = children
        return context

arche/templates/arche/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} My-Arche-Gui{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicons -->
	<meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet" />
    <link href="https://fundament.acdh.oeaw.ac.at/html/dist/fundament/css/fundament.min.css" rel="stylesheet" />
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="home contained fixed-nav" id="body">
    <div class="hfeed site" id="page">
        <div class="wrapper-fluid wrapper-navbar sticky-navbar" id="wrapper-navbar" itemscope="" itemtype="http://schema.org/WebSite">
            <a class="skip-link screen-reader-text sr-only" href="#content">Skip to content</a>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <!-- Your site title as branding in the menu -->
                    <a href="/" class="navbar-brand custom-logo-link" rel="home" itemprop="url">MyAGui
                    </a><!-- end custom logo -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"/>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                        <!-- Your menu goes here -->
                        <ul id="main-menu" class="navbar-nav">

                        </div>
                        <!-- .collapse navbar-collapse -->
                    </div>
                    <!-- .container -->
                </nav>
                <!-- .site-navigation -->
            </div>
           {% block content %}
           {% endblock %}
            <div class="wrapper fundament-default-footer" id="wrapper-footer-full">
                <div class="container-fluid" id="footer-full-content" tabindex="-1">
                    <div class="footer-separator">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle">
                            <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>
                        </svg> KONTAKT
                    </div>
                    <div class="row justify-content-md-center" style="text-align:center">
                        <div class="col">
                            <a href="https://www.oeaw.ac.at/acdh/" target="_blank" rel="noopener" aria-label="ACDH">
                                <img src="https://fundament.acdh.oeaw.ac.at/common-assets/images/acdh_logo.svg" alt="ACDH" title="Austrian Centre for Digital Humanities (ACDH) of the Austrian Academy of Sciences"/>
                            </a>
                            <br />
                            Austrian Centre for Digital Humanities (ACDH) of the Austrian Academy of Sciences
                        </div>
                      
                    </div>
                </div>
            </div>
            <div class="footer-imprint-bar" id="wrapper-footer-secondary" style="text-align:center; padding:0.4rem 0; font-size: 0.9rem;">
             
            </div>
            {% block scripts %}
            {% endblock %}
            {% block scripts2 %}
            {% endblock scripts2 %}
    </body>
</html>

arche/templates/arche/top_col_detail.html
{% extends "arche/base.html" %}
{% load static %}
{% block title %} {{ object.title }} {% endblock %}
{% load django_tables2 %}
{% block content %}
<div class="container">
    <div class="card imprint">
        <div class="card-header">
            <h1 style="text-align: center;">
                {% if lang %}
                {% for x in object.hasTitle %}
                    {% if x.property__lang == lang %}
                    {{ x.property__value }}
                    {% endif %}
                {% endfor %}
                {% else %}
                {{ object.hasTitle }}
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <p>
                {% for x in object.hasDescription %}
                    {% if x.property__lang == lang %}
                        {{ x.property__value }}
                    {% endif %}
                {% endfor %}
            </p>
           
            <ul>
                {% for key, value in object.items %}
                    
                <li>
                    {{ key }}
                    <ul>
                    {% for y in value %}
                        {% if y.property__object %}
                            {% for label in y.property__object %}
                            <li>
                                <a href="{{ label.arche_id }}">{{ label.label }} <small>{{label.label__lang}}</small></a>
                            </li>
                            {% endfor %}
                        {% else %}
                        <li>{{ y.property__value }}</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
            {% if children %}
            <div class="card">
                <div class="card-header">
                    <h3>Children</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        {% for key, item in children.items %}
                        <tr>
                                <td>
                                    <a href="{% url 'arche:top_col_detail' arche_id=key %}{% querystring %}">{{ key }}</a>
                                </td>
                                <td>
                                    {% for prop in item.hasTitle %}
                                        {{ prop.property__value }}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for prop in item.hasDescription %}
                                        {{ prop.property__value }}
                                    {% endfor %}
                                </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

arche/templates/arche/top_col_list.html
{% extends "arche/base.html" %}
{% load static %}
{% load django_tables2 %}

{% block title %} Arche TopCols {% endblock %}
{% block content %}
<div class="container">
    <div class="card imprint">
        <div class="card-body">
            <h1 style="text-align: center;">
                {{ top_cols|length }} Top - Collections
            </h1>
            <div class="row">
                {% for x in top_cols %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header" style="text-align: center;">
                            <img src="{{ x.arche_thumb }}" loading="lazy"/>
                            <h3><a href="{% url 'arche:top_col_detail' arche_id=x.arche_id %}{% querystring %}">{{ x.title }}</a></h3>
                            
                        </div>
                        <div class="card-body">
                            <p>{{ x.description|truncatechars:250 }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}